mex -I../src...
	-I/usr/local/include...
	-L/usr/local/lib...
	-L/usr/local/cuda/lib...
	-L/Applications/MATLAB_R2014a.app/bin/maci64/...
	../build/libloader_static.a...
	../build/libwrapper_static.a...
	../build/cunnproduction/libcunnproduction_static.a...
	-lcudart -lTH -lTHC -lmex -lmat -lmx...
	deepcompare.cpp
