% Uncomment this for OS X
% and put your paths to TH, THC and Matlab
%{
mex -I../src...
	-I/usr/local/include...
	-L/usr/local/lib...
	-L/usr/local/cuda/lib...
	-L/Applications/MATLAB_R2014a.app/bin/maci64/...
	../build/libloader_static.a...
	../build/libwrapper_static.a...
	../build/cunnproduction/libcunnproduction_static.a...
	-lcudart -lTH -lTHC -lmex -lmat -lmx...
	deepcompare.cpp
%}

% Linux
mex -I../src...
	-I/opt/rocks/distro/install/include...
	-L/opt/rocks/distro/install/lib...
	-L/usr/local/cuda/lib64...
	-L/usr/local/MATLAB/R2014a/bin/glnxa64...
        CXXFLAGS='-std=c++11 -fPIC'...
	../build/libwrapper_static.a...
	../build/libloader_static.a...
	../build/cunnproduction/libcunnproduction_static.a...
	-lcudart -lTH -lTHC -lmex -lmat -lmx...
	deepcompare.cpp
